### ISSUE TITLE
Environment setup for Ponymation

### ISSUE THREAD

**Issue by Friedrich-M** [3DAnimals/3DAnimals#8]
Thanks for your excellent works! Do you plan to release the conda environment setup of Ponymation?

**Comment by briannlongzhao** [comment]
Hi, environment setup for Ponymation also follows the steps listed in [INSTALL.md](https://github.com/3DAnimals/3DAnimals/blob/cb30fda354b402029ef70c9492516395bbac22d2/INSTALL.md#installation). If you use Weights & Biases for logging, you need to install wandb manually: `conda install wandb`. Please let us know if you run into any other problems.

**Comment by Friedrich-M** [comment]
Thanks for your reply!
